### ISSUE TITLE
Interpreter

### ISSUE THREAD

**Issue by tooolbox** [elsaland/elsa#8]
Nice project 👍 

I believe [Goja](https://github.com/dop251/goja) is 6-7x faster than [Otto](https://github.com/robertkrimen/otto) on average.  Any particular reason you chose Otto as the interpreter?

**Comment by divy-work** [comment]
Hey @tooolbox 
Elsa uses the Quickjs javascript engine (neither Goja or Otto). The reason for not choosing any of these was because Quickjs is much well established and faster than any native golang implementation. 

Although, Elsa is in it's very early stages of development and any major changes can be done before it is too late. Could you give me some point as to why we should use Goja? :)

**Comment by tooolbox** [comment]
Ah, my bad.  I saw Otto in your `go.mod` and made the assumption.

Looking at it, the only advantage of Goja over QuickJS is being pure Go.  If performance is a first-class goal (and I see now that it is) I believe you're on the right path with QuickJS :)

I suspect this will be killer in IoT.

**Comment by divy-work** [comment]
Yup, I'm working on getting ARM builds to work so we can have IoT support :smile:
