### ISSUE TITLE
Mandate lint and fmt in CI

### ISSUE THREAD

**Issue by littledivy** [elsaland/elsa#85]

**Comment by vidu171** [comment]
Hi, I would like to take this up.
Can you explain a bit more? What do you mean by mandate?

**Comment by littledivy** [comment]
@vidu171 Adding checks in the CI for checking `gofmt` & `prettier` formatting should do.

**Comment by vidu171** [comment]
Hi, are there any files that have to be added to .prettierignore?

**Comment by littledivy** [comment]
No, there is already a `.prettierignore ` https://github.com/elsaland/elsa/blob/master/.prettierignore

**Comment by sidntrivedi012** [comment]
Hey @vidu171 👋 , are you still working on this issue? Would love to take it up or maybe help out. Thanks :)

**Comment by littledivy** [comment]
Feel free to take this up @sidntrivedi012

**Comment by sidntrivedi012** [comment]
@littledivy I was thinking if we can use [ DeepSource Transformers](https://deepsource.io/transformers/) for formatting the code.  They support both Gofmt as well as Prettier. Alongwith that, we can also use the Analyzers which will perform the linting and static analysis of the code at every PR in order to maintain code quality.

I added both Gofmt and Prettier transformer and the Go and JS analyzer to my fork. And :
* Here is the PR that it created with the formatted code - https://github.com/siddhant-deepsource/elsa/pull/1
* Here are the issues that the analyzer reported - https://deepsource.io/gh/siddhant-deepsource/elsa/

I think it will be a great automation to maintain a single automated code quality and formatting across the project. Please take a look. The procedure to start using it is just adding a `deepsource.toml` file in the root of the repository. Thanks.
